### ISSUE TITLE
Why not merge with solarized repository?

### ISSUE THREAD

**Issue by pickfire** [seebi/dircolors-solarized#53]
I found https://github.com/altercation/solarized/ and couldn't find this [repository](https://github.com/seebi/dircolors-solarized) so maybe by putting this in the solarized repository will make people more easier to find the dircolors.

**Comment by seebi** [comment]
I'm not sure @altercation want a merge ... if you want, prepare this as a pull request.

**Comment by pickfire** [comment]
Yeah, he seems to be busy.
