### ISSUE TITLE
wrong ls color when using iterm2 ssh into linux(xubuntu) box

### ISSUE THREAD

**Issue by albertnetymk** [seebi/dircolors-solarized#65]
## Setup

1. Prepare iterm2 palette as instructed by https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized
2. Download `.dircolors` from https://github.com/seebi/dircolors-solarized/blob/master/dircolors.256dark

## How to reproduce

1. Open iterm2 on mac.
2. ssh <my-linux-server>
3. Apply dircolors, and invoke `ls` to see the output. 
![wrong](https://cloud.githubusercontent.com/assets/984374/11918236/a834c476-a763-11e5-81c4-7d231f99c2b4.png)

## Other info

* After launching tmux, the color becomes correct:
![right](https://cloud.githubusercontent.com/assets/984374/11918237/abb41584-a763-11e5-9e13-b0c444abf95c.png)

* Using uxterm (configured using https://github.com/solarized/xresources) on the server directly (without ssh) gives me the correct color both outside and inside tmux.

## ENV

Server (linux) OS: Ubuntu 14.03
Mac: 10.9.5
iterm2: 2.1.4
Shell: zsh

**Comment by seebi** [comment]
hi @albertnetymk, is this issue still relevant? I can't reproduce it ...

**Comment by seebi** [comment]
pls reopen if you still have a problem

**Comment by albertnetymk** [comment]
It turns out to be an issue in [mosh](https://github.com/mobile-shell/mosh/issues/500). I recalled that I could reproduce the bug even in ssh, but I guess I was wrong. Sorry for the noise. Thank you very much for the work.
