### ISSUE TITLE
SOCK hard to read (magenta on blue)

### ISSUE THREAD

**Issue by blueyed** [seebi/dircolors-solarized#66]
Sockets get colored using `SOCK 35;44`, which translates to magenta on blue.

Given that the intention here is to have a blue background, I'd say to use `37;44` as with `CHR` here, too.

It might be better to use `01;37;44` (bright white) here even.

`BLK  33;44` is also problematic (33=yellow).

**Comment by seebi** [comment]
I agree, pls send pull request ...
