### ISSUE TITLE
Correction README.md: General Instruction

### ISSUE THREAD

**Issue by dunnodun** [seebi/dircolors-solarized#71]
> The Solarized color themes are distributed as database files for GNU dircolors, which is the application that sets up colors for GNU ls. To use any of the database files, run this:
> 
> eval `dircolors /path/to/dircolorsdb`
> To activate the theme for all future shell sessions, copy or link that file to ~/.dir_colors, and include the above command in your ~/.profile (for bash) or ~/.zshrc (for zsh).

If you do add "eval `dircolors /path/to/dircolorsdb`", xrdb will return "xrdb: colon missing on line 1, ignoring line". Not an error, but some may stumble over it. 
"eval: `dircolors /path/to/dircolorsdb`" should be written there.

**Comment by seebi** [comment]
can you give me the output of just `dircolors /path/to/dircolors.256dark ` or whatever theme you used?

**Comment by dunnodun** [comment]
F*** now I forgot, on which system I did those changes. 

But from the look now everything's fine how it's described in the README. Sorry for wasting your time.
