### ISSUE TITLE
ansi-universal and ansi-light show 0777 folders in bad color combination

### ISSUE THREAD

**Issue by jonascj** [seebi/dircolors-solarized#73]
I'm changing between dark and light solarized theme in my terminal emulator (termite) and I wanted to change dircolors as well, but I've noticed that dircolors.ansi-light and dircolors.ansi-universal cause 0777 folders to be drawn in a bad color combination (blue on yellow). See these screenshots demonstrating the weird colors of universal and light, and the good colors of dark:

http://imgur.com/gallery/U0Kvz

Is that a fault on my end, or just an unfortunate color combination nobody has noticed before? After all 0777 folders are rare, and maybe few users use the light themes.

Please advise if you need more information about my setup. I can dump values of $LS_COLORS etc. if you need them.

The fact that it looks nice with the ansi-dark theme leads me to believe I have my terminal emulator colors configured correctly, and the right boldfont settings.

**Comment by jonascj** [comment]
So it appears there is no "OTHER_WRITEABLE" color set in dircolors.ansi-light. 
Might I suggest "OTHER_WRITABLE 34;47" in the light theme?

**Comment by seebi** [comment]
@jonascj pr is merged, thanks for the note ...
