### ISSUE TITLE
Help needed / presumably bug: Is this the correct colors?

### ISSUE THREAD

**Issue by ghost** [seebi/dircolors-solarized#77]
[How the dircolors color scheme looks on my terminal](https://raw.githubusercontent.com/kalterfive/resources/master/20170425203346-31198.png)

_Take look at /dev/sd* and /tmp/tmux/*_ - the color mix looks ugly.

I found out that these colors are not correct. For example, [in this screenshot](https://lh3.googleusercontent.com/-z4lQU3dxDkw/UWVyKBF641I/AAAAAAAAXZ0/rjYz7tHEQUc/w530-h458-p/gnome-terminal-solarized.png), colors are different from the ones I have.

I did not find my mistakes in whether I installed the color theme correctly, and so I guess there is a bug in the color scheme; I also tried different terminals - the result is the same.

My setup:
 - GNOME Terminal 3.24.1 (also tried rxvt-unicode 9.22)
 - TERM=screen-16color (also tried rxvt-* and *-255color)
 - dircolors.ansi-dark (also tried ansi-light)

I made a mistake? Or/and is this a known problem?

**Comment by seebi** [comment]
screenshots not available anymore - will close for now. sorry.
