### ISSUE TITLE
how do i change colors for Directories with permissions drwxrwsrwx

### ISSUE THREAD

**Issue by eg020571** [seebi/dircolors-solarized#81]
![image](https://user-images.githubusercontent.com/31349364/29717178-d1906374-89cb-11e7-8871-c21e4f9ae28a.png)

I am unable to read directories names which have  drwxrwsrwx  permissions with green background ,Can someone suggest some alternative .
i am using solarized dark theme in terminal.

**Comment by seebi** [comment]
IMHO - the background color comes from the sticky bit. can you remove it and check again?

**Comment by mhall** [comment]
This is an issue for me too, and appears to show up for all directories that are other-writable.

**Comment by seebi** [comment]
can you please play around with these lines

```
STICKY_OTHER_WRITABLE 48;5;64;38;5;230 # dir that is sticky and other-writable (+t,o+w)
OTHER_WRITABLE 48;5;235;38;5;33 # dir that is other-writable (o+w) and not sticky
STICKY 48;5;33;38;5;230 # dir with the sticky bit set (+t) and not other-writable
```
