### ISSUE TITLE
Is ",v" format error?

### ISSUE THREAD

**Issue by delta4d** [seebi/dircolors-solarized#82]
I found `,v` in color file:

```
➜  dircolors-solarized git:(master) git grep -w ',v'
dircolors.ansi-dark:#*,v 01;36
dircolors.ansi-dark:*,v 01;33
dircolors.ansi-light:*,v 01;36
dircolors.ansi-light:#*,v 01;33
dircolors.ansi-universal:*,v 01;36
dircolors.ansi-universal:#*,v 01;33
```

Is this meant to match `*.v` ? Or it has its own meaning?

**Comment by Toriansel** [comment]
This change was incorrect.  RCS (an old school Unix file based revision control system) files use ,v as the file extension. If .v is also an extension, both should be represented. Sorry, I am like 5 years behind in updating my .dircolors file.

**Comment by seebi** [comment]
`¯\_(ツ)_/¯`
