### ISSUE TITLE
Bold fonts no longer working

### ISSUE THREAD

**Issue by dunnl** [seebi/dircolors-solarized#83]
I don't understand the merge from issue #44. It would seem that the change was just to get rid of the bold font hierarchy that is still described in the README. I believe the user who submitted the change was simply having an issue whereby a particular terminal was not displaying bold fonts properly and simply giving them a dark background, but on Xfce4-term (e.g.) the commit simply gets rid of having bold fonts for certain files.

Submitting this as a new issue because I'm not sure which version is preferred by others, but anyway there's at least an inconsistency in the README vs the current state of the repo.

**Comment by xa0c** [comment]
Can't understand that f5910a6 commit either. Was using my own custom-modified version of `dircolors.dark` since then. And actually looks like that commit just switched bold fonts to normal (`01` to `00`). While #44 issue is related to background colors.

**Comment by uralets** [comment]
can confirm - f5910a6 really is an unfortunate commit and looks just plain erroneous.
@seebi

**Comment by scotstan** [comment]
Can confirm here too: f5910 was likely a mistake. Considering this issue was opened 2+ years ago, wondering if it's still being maintained?

**Comment by seebi** [comment]
Can you send a merge request please?

**Comment by scotstan** [comment]
Hey @seebi: I was just logging back in to send you a PR on this one, only to see it's already closed! Thanks for fixing.

As I was working on this last night, I had issues on macOS failing with gnu tar on unpacking two of the special files: nod-c and nod-b. With tar failing, the Makefile would quit, so I added a "-" at the beginning of the recipe step.  

Anyway, here's my branch:
https://github.com/scotstan/dircolors-solarized

I'm open to pulling back from your main and sending a new PR if you're interested.

**Comment by seebi** [comment]
sure, do this. thx
