### ISSUE TITLE
License for seebi/dircolors-solarized?

### ISSUE THREAD

**Issue by phongvcao** [seebi/dircolors-solarized#90]
Hi seebi,

Thank you for the great work on dircolors-solarized. I really want to use your script at work but my employer requires that dircolors-solarized has an explicit open-source license on Github page. So far I see that dircolors.256dark has a license (even though not GPL / MIT). Can you add license to the whole repo or to the other dircolors.ansi-* files? Thank you for your work.

**Comment by seebi** [comment]
ok, added a standard MIT License
