### ISSUE TITLE
Different colors in Visual Studio Code vs. WSL terminal

### ISSUE THREAD

**Issue by pstuermlinger** [seebi/dircolors-solarized#94]
[Screenshot](https://i.imgur.com/4Q225yQ.png)
I'm using the 256dark theme, which is loaded by ```eval `dircolors ~/.dircolors` ``` in `.zshrc`.

As you see, the background color of the current path is different, even though both versions get their color settings the same way. Is there a fix for this? It should be as in VSC.

Kind regards
Patrick

**Comment by seebi** [comment]
I assume there is no way to fix this ...
